export const FETCH_CARD_REQUEST = 'FETCH_CARD_REQUEST';
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const FETCH_CARD_FAILED = 'FETCH_CARD_FAILED';

export const FETCH_CARD_CATEGORYS_REQUEST = 'FETCH_CARD_REQUEST';
export const FETCH_CARD_CATEGORYS_SUCCESS = 'FETCH_CARD_SUCCESS';
export const FETCH_CARD_CATEGORYS_FAILED = 'FETCH_CARD_FAILED';

export const FETCH_CARD_ADD = 'FETCH_CARD_ADD';

export const SEARCH_CARDS = 'SEARCH_CARDS';


